[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "pybind11>=2.8.0",
]

build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
test-command = "cd {project}/python-package && pytest tests"
test-skip = "*universal2:arm64"
before-all = ["git clone https://gitlab.com/libeigen/eigen.git"]

[tool.cibuildwheel.windows]
test-command = "pytest {project}/python-package/tests"
