name: Wheels

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
     - main
  release:
    types:
      - published

jobs:
  build_sdist:
    name: Build SDist
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./python-package
    steps:
    - uses: actions/checkout@v4

    - name: Build SDist
      run: pipx run build --sdist

    - name: Check metadata
      run: |
         pipx run twine check dist/*
         pwd
         ls -lah dist

    - uses: actions/upload-artifact@v4
      with:
        name: sdist-artifact
        path: ${{ github.workspace }}/python-package/dist/*.tar.gz

  build_wheels:
    name: Wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    defaults:
      run:
        working-directory: ./python-package

    steps:
    - uses: actions/checkout@v4

    - uses: pypa/cibuildwheel@v2.17.0
      with:
        package-dir: python-package
      env:
        CIBW_ARCHS_MACOS: auto universal2
        CIBW_ARCHS: auto64
        CIBW_TEST_EXTRAS: "dev"

    - name: Verify clean directory
      run: git diff --exit-code
      shell: bash

    - name: Upload wheels
      uses: actions/upload-artifact@v4

      with:
        name: wheel-artifacts-${{ matrix.os }}
        path: wheelhouse/*.whl

  upload:
    name: Upload
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'published'

    steps:
    - uses: actions/setup-python@v5

    - uses: actions/download-artifact@v4
      with:
        name: wheel-artifacts*
        path: dist

    - uses: pypa/gh-action-pypi-publish@v1.8.14
      with:
        user: __token__
        password: ${{ secrets.pypi_password }}
